### ISSUE TITLE
loading bar now shown fully below 400ish px width

### ISSUE THREAD

**Issue by dtorrenp** [Imperial-visualizations/Vue-Components#24]
when the bar shooter than  around 400px it no longer shows full width might be an issue for someone on a small screen

**Comment by darrenlean** [comment]
> when the bar shooter than around 400px it no longer shows full width might be an issue for someone on a small screen

Hey Dan, do you mind including a screenshot?

**Comment by darrenlean** [comment]
This is now resolved in pull request #30
